# Sidebar navigation

- label: "Welcome"
  link: "/"
- label: "Online tool"
  link: "/create"
- label: "As a dependency"
  items:
    - label: "Install"
      link: "/package/install"
    - label: "Docs"
      link: "/usage/docs"
- label: "Web API"
  items:
    - label: "Example"
      link: "/webapi"
    - label: "Docs"
      link: "/webapi/docs"
- label: "External"
  items:
    - label: "Github"
      link: "https://github.com/rocketseat/gatsby-themes"
